//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_JSBT_HsinChu101.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Student_JSBT_HsinChu101.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;原住民&quot; ItemValue=&quot;1&quot; /&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;派外人員子女&quot; ItemValue=&quot;2&quot; /&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;蒙藏生&quot; ItemValue=&quot;3&quot; /&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;回國僑生&quot; ItemValue=&quot;4&quot; /&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;港澳生&quot; ItemValue=&quot;5&quot; /&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;退伍軍人&quot; ItemValue=&quot;6&quot; /&gt;
        ///  &lt;Data FieldName=&quot;學生身分&quot; StudTag=&quot;&quot; ItemName=&quot;境外優秀科學技術人才子女&quot; ItemValue=&quot;7&quot; /&gt;
        ///  &lt;Data [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StudentJSBT_conf {
            get {
                return ResourceManager.GetString("StudentJSBT_conf", resourceCulture);
            }
        }
    }
}
