//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3082
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHPermrec.UpdateRecord.GovernmentalDocument {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GDResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GDResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHPermrec.UpdateRecord.GovernmentalDocument.GDResources", typeof(GDResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btnItemNameList_Image {
            get {
                object obj = ResourceManager.GetObject("btnItemNameList_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] JContinueStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("JContinueStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JEnrollmentListTemplate {
            get {
                object obj = ResourceManager.GetObject("JEnrollmentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JEnrollmentListTemplate_HsinChu {
            get {
                object obj = ResourceManager.GetObject("JEnrollmentListTemplate_HsinChu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JEnrollmentListTemplate_TaiChung {
            get {
                object obj = ResourceManager.GetObject("JEnrollmentListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JExtendingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("JExtendingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JGraduateListTemplate_HsinChu {
            get {
                object obj = ResourceManager.GetObject("JGraduateListTemplate_HsinChu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JGraduateListTemplate_TaiChung {
            get {
                object obj = ResourceManager.GetObject("JGraduateListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JGraduatingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("JGraduatingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JResumeStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("JResumeStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JSuspensionStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("JSuspensionStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JTransfer01ListTemplate_HsinChu {
            get {
                object obj = ResourceManager.GetObject("JTransfer01ListTemplate_HsinChu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JTransferListTemplate_TaiChung {
            get {
                object obj = ResourceManager.GetObject("JTransferListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JTransferring01StudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("JTransferring01StudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JTransferringStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("JTransferringStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JTransferStudentUpdateRecordTemplate_HsinChu {
            get {
                object obj = ResourceManager.GetObject("JTransferStudentUpdateRecordTemplate_HsinChu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JUpdateStudentPermrecTemplate {
            get {
                object obj = ResourceManager.GetObject("JUpdateStudentPermrecTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] JUpdateStudentPermrecTemplate_KH
        {
            get
            {
                object obj = ResourceManager.GetObject("JUpdateStudentPermrecTemplate_KH", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] JDeadStudentListTemplate
        {
            get
            {
                object obj = ResourceManager.GetObject("JDeadStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] JResumeListTemplate_TaiChung
        {
            get
            {
                object obj = ResourceManager.GetObject("JResumeListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] JTransfer01ListTemplate_TaiChung
        {
            get
            {
                object obj = ResourceManager.GetObject("JTransfer01ListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] JExtendListTemplate_TaiChung
        {
            get
            {
                object obj = ResourceManager.GetObject("JExtendListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] JUpdateStudentPermrecListTemplate_TaiChung
        {
            get
            {
                object obj = ResourceManager.GetObject("JUpdateStudentPermrecListTemplate_TaiChung", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
