//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34011
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHPermrec.UpdateRecord.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHPermrec.UpdateRecord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap contract_zoom_128 {
            get {
                object obj = ResourceManager.GetObject("contract_zoom_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立育才國小&quot; Code=&quot;011601&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立聖心國小&quot; Code=&quot;011602&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立及人國小&quot; Code=&quot;011603&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立竹林國小&quot; Code=&quot;011604&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立信賢種籽親子實小&quot; Code=&quot;011606&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;私立裕德國小&quot; Code=&quot;011607&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國小&quot; Code=&quot;014601&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立國光國小&quot; Code=&quot;014602&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string eh {
            get {
                return ResourceManager.GetString("eh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap graduated_write_64 {
            get {
                object obj = ResourceManager.GetObject("graduated_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap history_save_64 {
            get {
                object obj = ResourceManager.GetObject("history_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SchoolList&gt;
        ///  &lt;School Name=&quot;私立時雨國中&quot; Code=&quot;011501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立板橋國中&quot; Code=&quot;014501&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立重慶國中&quot; Code=&quot;014503&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立江翠國中&quot; Code=&quot;014504&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立中山國中&quot; Code=&quot;014505&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新埔國中&quot; Code=&quot;014506&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新莊國中&quot; Code=&quot;014507&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立新泰國中&quot; Code=&quot;014508&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Name=&quot;市立 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string jh {
            get {
                return ResourceManager.GetString("jh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loading5 {
            get {
                object obj = ResourceManager.GetObject("loading5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap user_write_64 {
            get {
                object obj = ResourceManager.GetObject("user_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 台中轉入Template {
            get {
                object obj = ResourceManager.GetObject("台中轉入Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
