//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHPermrec.UpdateRecord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JHPermrec.UpdateRecord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contract_zoom_128 {
            get {
                object obj = ResourceManager.GetObject("contract_zoom_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SchoolList&gt;
        ///  &lt;School Code=&quot;011301&quot; Name=&quot;私立淡江高中附設國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011302&quot; Name=&quot;私立康橋高中附設國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011307&quot; Name=&quot;新北市裕德高級中等學校附設國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011330&quot; Name=&quot;新北市林口康橋高中附設國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011601&quot; Name=&quot;私立育才國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011602&quot; Name=&quot;私立聖心國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011603&quot; Name=&quot;私立及人國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011604&quot; Name=&quot;私立竹林國小&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011606&quot; Name=&quot;私立信賢 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eh {
            get {
                return ResourceManager.GetString("eh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graduated_write_64 {
            get {
                object obj = ResourceManager.GetObject("graduated_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history_save_64 {
            get {
                object obj = ResourceManager.GetObject("history_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SchoolList&gt;
        ///  &lt;School Code=&quot;010301&quot; Name=&quot;國立華僑高級中等學校附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011301&quot; Name=&quot;私立淡江高中附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011302&quot; Name=&quot;私立康橋高中附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011306&quot; Name=&quot;私立金陵女中附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011307&quot; Name=&quot;新北市裕德高級中等學校附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011309&quot; Name=&quot;財團法人南山高中附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011310&quot; Name=&quot;財團法人恆毅高中附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Code=&quot;011311&quot; Name=&quot;私立聖心女中附設國中&quot; County=&quot;新北市&quot; /&gt;
        ///  &lt;School Cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jh {
            get {
                return ResourceManager.GetString("jh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading5 {
            get {
                object obj = ResourceManager.GetObject("loading5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_write_64 {
            get {
                object obj = ResourceManager.GetObject("user_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
